global:
  smtp_smarthost: "mail.gmx.net:587"
  smtp_from: "rainer.doelker@gmx.net"
  smtp_auth_username: "rainer.doelker@gmx.net"
  smtp_auth_password_file: /etc/alertmanager/smtp_password.secret
  smtp_require_tls: true
 
route:
  receiver: email-me
 
receivers:
- name: email-me
  email_configs:
  - to: "rainer.doelker@gmx.net"
