worker_processes  1;
events { worker_connections  1024; }
 
http {
    upstream slow_cluster {
        server slow-api:8080;
        server slow-api_2:8080;
        server slow-api_3:8080;
    }
 
    server {
        listen 80;
 
        # Round-robin to the slow /work endpoint
        location /work {
            proxy_pass http://slow_cluster;
        }
 
        # Nginx counters for the exporter
        location /nginx_status {
            stub_status;
            allow all;
        }
    }
}
